# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1fe4c27cbe4eec75348934cbacd9e095049a98c0e6ff22a9305ea165906a26b68d3070747ed5ffe5a4ae4b21f76da4b366dbd278fc507dff90ac54bbae45bcf

test:
  secret_key_base: 4442998ad2573b6a120ac5d5dae017f59d21b4eeb52f73e8045554cc9d3099a7f04b4b423abcf2a2f6fcbb14fc2d112fa6907b03cd3acc50eb55795c7620f5af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
