class AddFieldsToJobApplication < ActiveRecord::Migration
  def change
    add_column :job_applications, :nickname, :string
    add_column :job_applications, :address, :string
    add_column :job_applications, :apt, :string
    add_column :job_applications, :city, :string
    add_column :job_applications, :us_state, :string
    add_column :job_applications, :zip, :string
    add_column :job_applications, :full_time, :boolean
    add_column :job_applications, :part_time, :boolean
    add_column :job_applications, :available_as_of, :string
    add_column :job_applications, :emergency_name, :string
    add_column :job_applications, :emergency_day_phone, :string
    add_column :job_applications, :emergency_night_phone, :string
    add_column :job_applications, :employer1, :string
    add_column :job_applications, :supervisor1, :string
    add_column :job_applications, :employer1_phone, :string
    add_column :job_applications, :from1, :string
    add_column :job_applications, :to1, :string
    add_column :job_applications, :salary1, :string
    add_column :job_applications, :employer_address1, :string
    add_column :job_applications, :title1, :string
    add_column :job_applications, :reason1, :string
    add_column :job_applications, :employer2, :string
    add_column :job_applications, :supervisor2, :string
    add_column :job_applications, :employer2_phone, :string
    add_column :job_applications, :from2, :string
    add_column :job_applications, :to2, :string
    add_column :job_applications, :salary2, :string
    add_column :job_applications, :employer_address2, :string
    add_column :job_applications, :title2, :string
    add_column :job_applications, :reason2, :string
    add_column :job_applications, :employer3, :string
    add_column :job_applications, :supervisor3, :string
    add_column :job_applications, :employer3_phone, :string
    add_column :job_applications, :from3, :string
    add_column :job_applications, :to3, :string
    add_column :job_applications, :salary3, :string
    add_column :job_applications, :employer_address3, :string
    add_column :job_applications, :title3, :string
    add_column :job_applications, :reason3, :string
    add_column :job_applications, :high_school_years, :string
    add_column :job_applications, :high_school_name, :string
    add_column :job_applications, :high_school_degree, :string
    add_column :job_applications, :tech_years, :string
    add_column :job_applications, :tech_name, :string
    add_column :job_applications, :tech_degree, :string
    add_column :job_applications, :trade_years, :string
    add_column :job_applications, :trade_name, :string
    add_column :job_applications, :trade_degree, :string
    add_column :job_applications, :business_years, :string
    add_column :job_applications, :business_name, :string
    add_column :job_applications, :business_degree, :string
    add_column :job_applications, :college_years, :string
    add_column :job_applications, :college_name, :string
    add_column :job_applications, :college_degree, :string
    add_column :job_applications, :graduate_years, :string
    add_column :job_applications, :graduate_name, :string
    add_column :job_applications, :graduate_degree, :string
    add_column :job_applications, :cert1, :string
    add_column :job_applications, :cert_state1, :string
    add_column :job_applications, :cert_date1, :string
    add_column :job_applications, :cert2, :string
    add_column :job_applications, :cert_state2, :string
    add_column :job_applications, :cert_date2, :string
    add_column :job_applications, :cert3, :string
    add_column :job_applications, :cert_state3, :string
    add_column :job_applications, :cert_date3, :string
    add_column :job_applications, :cert4, :string
    add_column :job_applications, :cert_state4, :string
    add_column :job_applications, :cert_date4, :string
    add_column :job_applications, :convicted, :boolean
    add_column :job_applications, :convicted_explanation, :string
    add_column :job_applications, :learn_ad, :boolean
    add_column :job_applications, :learn_ad_explanation, :string
    add_column :job_applications, :learn_employee, :boolean
    add_column :job_applications, :learn_employee_explanation, :string
    add_column :job_applications, :learn_other, :boolean
    add_column :job_applications, :learn_other_explanation, :string
    add_column :job_applications, :previously_worked, :string
    add_column :job_applications, :previously_worked_explanation, :string
    add_column :job_applications, :reference1_name, :string
    add_column :job_applications, :reference1_relationship, :string
    add_column :job_applications, :reference1_address, :string
    add_column :job_applications, :reference1_phone, :string
    add_column :job_applications, :reference2_name, :string
    add_column :job_applications, :reference2_relationship, :string
    add_column :job_applications, :reference2_address, :string
    add_column :job_applications, :reference2_phone, :string
    add_column :job_applications, :reference3_name, :string
    add_column :job_applications, :reference3_relationship, :string
    add_column :job_applications, :reference3_address, :string
    add_column :job_applications, :reference3_phone, :string
    add_column :job_applications, :signature, :string
    add_column :job_applications, :sig_date, :string
  end
end
